### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by linc0380** [jrnold/masteringmetrics#2]
Hi Jeffrey,

I was very excited to see your work on porting the empirical analysis in Mastering Metrics to R. Yet I do not succeed in running
```
devtools::install_github("jrnold/masteringmetrics", subdir = "masteringmetrics")
```
All packages identified as missing or outdated on my system are successfully installed. At the end, however, I get
```
✔  checking for file ‘/tmp/Rtmpap4PJH/remotes23733c70b5/jrnold-masteringmetrics-d7c2b06/masteringmetrics/DESCRIPTION’ ...
─  preparing ‘masteringmetrics’:
E  checking DESCRIPTION meta-information ...
   Malformed Authors@R field:
     <text>:2:0: unexpected end of input
   1: c(person("Jeffrey", "Arnold", , "jeffrey.arnold@gmail.com", c("aut", "cre"))
      ^
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error: Failed to install 'masteringmetrics' from GitHub:
  System command error, exit status: 1, stderr empty
```
This is on a system running `R version 3.5.1 (2018-07-02) -- "Feather Spray"`.

When trying the same installation on a system running `R version 3.6.0 (2019-04-26) -- "Planting of a Tree"` I can similarly install all required packages but then, at the end, get
```
Error: Failed to install 'masteringmetrics' from GitHub:
  lazy-load database '/home/michael/R/x86_64-pc-linux-gnu-library/3.6/callr/R/callr.rdb' is corrupt
In addition: Warning message:
In get0(oNam, envir = ns) : internal error -3 in R_decompress1
```

I am at a complete loss as to what either of these messages mean. Can you help out?

Thanks,
Michael

**Comment by jrnold** [comment]
Sorry, this was just a typo in the file that kept it from working. Fixed now!

**Comment by linc0380** [comment]
Thanks a lot for this, Jeffrey!

Regards,
Michael
